version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - .database/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.2
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_city_link:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - .database/redis:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3024:8080

volumes:
  mongodb_city_link:
